// Module imports
import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { type PropsWithChildren } from 'react'

import '@radix-ui/themes/styles.css'

// Local imports
import { RootLayout } from '@/components/RootLayout/RootLayout'
import { ThemeProvider } from '@/context/ThemeProvider/ThemeProvider'

import './globals.css'

// Types
type Props = Readonly<PropsWithChildren>

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayoutWrapper(props: Props) {
	const { children } = props

	return (
		<html
			lang={'en'}
			suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<ThemeProvider
					attribute={'class'}
					defaultTheme={'system'}
					enableSystem
					disableTransitionOnChange>
					<RootLayout>{children}</RootLayout>
				</ThemeProvider>
			</body>
		</html>
	)
}
