// Module imports
import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { type PropsWithChildren } from 'react'
import { Theme } from '@radix-ui/themes'

import '@radix-ui/themes/styles.css'

// Local imports
import { AuthManager } from '@/components/AuthManager/AuthManager'
import { RootLayout } from '@/components/RootLayout/RootLayout'

import './globals.css'

// Types
type Props = Readonly<PropsWithChildren>

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayoutWrapper(props: Props) {
	const { children } = props

	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AuthManager />

				<Theme
					// accentColor={'sky'}
					appearance={'dark'}
					// radius={'none'}
				>
					<RootLayout>{children}</RootLayout>
				</Theme>
			</body>
		</html>
	)
}
